### ISSUE TITLE
Add control to skip to the next day

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#116]
Add a confirmation box first.

**Comment by theSeb1979** [comment]
Set time the next day (6 am or 7 am etc)?

**Comment by joskuijpers** [comment]
Cant just set the time. That will break all the things. We need to call all the minute and hour and day change listeners. But it is really troublesome because the game isn’t made for this.

**Comment by Dzi4d3k** [comment]
I'm just curious why your really need this if there is Fast Forward mod which advance time in x12000 scale where skipping a day is matter of couple of seconds.

**Comment by redrummed1** [comment]
Sorry guys for thread jacking but I use the time fast forward mod, seems to do the job perfect, takes about 20seconds to go through a day. Keep up the amazing work!

**Comment by redrummed1** [comment]
Dzi4d3k just beat me to it man!!

**Comment by joskuijpers** [comment]
Stuff can really break at x12000. Also really depends on what mod you use for it.

**Comment by Dzi4d3k** [comment]
I think I know what you mean, because of this we are using FF mod in jumps advance few (3-5 hours) wait for couple of seconds (especially to observe map synchronization)  and again. Not sure about SP but in MP it is needed to allow one growth stage to get synchronized with clients before next growth stage.

**Comment by joskuijpers** [comment]
We will leave this out
