### ISSUE TITLE
Fill (and implement) the GUI help view

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#134]
We might just skip this and do it later. It is not really important. I still have to figure out how to make it work as well.

**Comment by TyKonKet** [comment]
Take a look at this:
https://github.com/TyKonKet/FS17_CreatorTools/blob/master/src/helpers/helpLineLoader.lua
and this:
https://github.com/TyKonKet/FS17_CreatorTools/blob/master/src/helpline/helpLine.xml

**Comment by joskuijpers** [comment]
Thanks! That helps a lot :)

**Comment by TyKonKet** [comment]
I think you should take a choice:
1) Implement this help as a different GUI, exactly as it is now, as third page of the mod panel. This will take several time, because we will need to reimplement the behaviour of helpLine GUI.
2) Integrate this help with in game helpLine by adding your help categories, this is what I've done with my mod Creator Tools and in my opinion is not bad.
Let me know what you prefer to do and I'll try to implement the needed code if you agree.

**Comment by joskuijpers** [comment]
Hi!

We chose option 2 and as you might have noticed, I have also implemented it already :) Now we are working on writing the texts.

I didn't copy your code but I can add you to the credits if you want.

**Comment by TyKonKet** [comment]
Nono, you will add me to credits when I'll do something of real :)
