### ISSUE TITLE
Show ingame notification when animals die

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#195]
Using `g_currentMission:addIngameNotification`

**Comment by joskuijpers** [comment]
Done.
Sadly it shows '1 animals have died': but getting the translation right for all languages is a pain so I'll keep it.

**Comment by Dzi4d3k** [comment]
Maybe change to something like this:
"Your animals are dieing (already died %d)", however I dunno what quantifier can be used in terms of animals.
This test will fit in Polish translation as I would used "%d szt." which translate to pcs., but pcs in English doesn't fit for animals, rather for non-living items.
However this suggestion is similar to what @Gonimy-Vetrom did in 0210df2, because he didn't translated this message directly as I did.

**Comment by joskuijpers** [comment]
I now use: "Animals died (1)"
