### ISSUE TITLE
[GM] Implement spring barley and spring wheat 

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#27]
Initial analysis thread
https://github.com/theSeb1979/FS17_seasons/issues/3

**Comment by mrbear** [comment]
If we implement a custom growth manager with a walking square manipulating density layers we could freeze the growth for wheat/barley below a specific growth state and wither the rest if the season is winter. 

I.e If we manage growth in our code instead of Giants code we are free to decouple us from the linear flow of incrementing states that increment every cycle in the base game.

**Comment by theSeb1979** [comment]
That's my intention after looking through upsidedown's growth manager mod

**Comment by theSeb1979** [comment]
Implemented
