### ISSUE TITLE
Our impressions on the seasonsmod

### ISSUE THREAD

**Issue by SimulatorGAMES** [RealismusModding/FS17_seasons#307]
Hello,
My name is Hugo I am modder / mapper in a "team" of 4 players ...                                                                       Sorry for my writing, I am french ^^

We are serious players, we play RolePlay in multiplayer since FS 2008 , this is our job: 
- https://lafermeduchambret.jimdo.com/
- https://www.facebook.com/LaFermeDuChambret
- https://www.youtube.com/user/ChantierTravaux

We use your mod on dedicated server "verygame". And we are very satisfied at the moment, bravo! We do a lot of testing with the settings:
12 days a season and time in X120 without the fastForward mod

We found a few points to review ...
- Have the possibility to choose which season one wants to start on a new backup, and not be obliged to start in spring.
- The mod and incompatible with the mod "LocoDrive.zip"
- Remove the fact that "FoliageSubLayer = grass" and "FoliageMultiLayer =xxxxxxx" can be deleted with a cultivator in a meadow or on the roadside.
- Add the textures of the FS15 trees in the seasons
- Games that often stop around 00:00 when crops change from stage of growth.
- And it would be necessary that in the middle of the summer one can harvest wheat, barley, rape

Thank you for reading, and thanks for the work you have already done...
Bye ,
Hugo ,

**Comment by joskuijpers** [comment]
Thank you!

> Have the possibility to choose which season one wants to start on a new backup, and not be obliged to start in spring.
This is not possible: too complicated. We decided on spring because it is the start of the year so  you can cultivate and plant. Starting in summer means you can't do anything until spring, same for autumn and winter.
Remember that Seasons needs to reset all your crops when a new game starts.

> The mod and incompatible with the mod "LocoDrive.zip"
Can you give us a link to the mod so we can test?

> Remove the fact that "FoliageSubLayer = grass" and "FoliageMultiLayer =xxxxxxx" can be deleted with a cultivator in a meadow or on the roadside.
I am not sure what you mean. Can you elaborate?

> Add the textures of the FS15 trees in the seasons
This is up to KimG, if he is willing to put the time into it. We won't be putting it in Seasons directly though, but they would then be available as a Seasons Texture Mod. Otherwise the mod package is getting too big.

> Games that often stop around 00:00 when crops change from stage of growth.
This is because you play at 120x. We do a lot of stuff at midnight and we already tried to minimize the impact. Everything below 120x gives almost no issues.

> And it would be necessary that in the middle of the summer one can harvest wheat, barley, rape
You are able to override our growth.xml with your own growth system. We are not changing the growth we have by default.

**Comment by SimulatorGAMES** [comment]
Hello ! Thank you for your answers :)

Here is the link of the mod locodrive, this mod allows the locomotive to roll all alone all the time.
http://www.farming2015mods.com/farming-simulator-2017-mods/fs17-other/fs17-locodrive/

What I wanted to say for the FoliageSubLayer is that you can delete the decorative foliages and the grass with a cultivator, while on the base games do not. It's embarrassing because when working in a field it destroys the decorartion foliage around the field...

**Comment by joskuijpers** [comment]
We made an update just now that might fix your issue. When I run a cultivater over grass (non-field), the grass remains.

I will take a look at the train thing

**Comment by joskuijpers** [comment]
I installed the LocoDrive and it works just fine with Seasons. No problems whatsoever.
You need to be in the train to activate the LocoDrive thing. (it is active by default)
