### ISSUE TITLE
Change the duration of a season?

### ISSUE THREAD

**Issue by SimulatorGAMES** [RealismusModding/FS17_seasons#311]
I have another question, sorry 
Is it possible to change the length of a season?
We would like more than 12 days, 
If possible, where should we change?

**Comment by joskuijpers** [comment]
Euh it is possible to change it in the savegame.

However, I suggest you just lower your speed to 30x instead.
We have not tested any of our algorithms and code with seasons longer than 12.
Also, changing season length by hand causes many problems on existing savegames (which is why we have a special system to change it builtin)

Make backups
