### ISSUE TITLE
Which values to change in the file growth.xml 

### ISSUE THREAD

**Issue by SimulatorGAMES** [RealismusModding/FS17_seasons#339]
Hello 
What are the values to put in order to be able to sow barley during the early spring and throughout the autumn and harvest it all summer.
And for rape, it possible can be sow from late summer to early autumn and harvested all summer.

As the arrows in the pictures...
http://www.hostingpics.net/viewer.php?id=7103571111.png

It's possible please ?

**Comment by theSeb1979** [comment]
Currently barley can be sown in early spring and all transitions of autumn. Harvesting is only possible from late summer. Basically, if you want to harvest it sooner then you have to get it to stage 7 quicker

Rape can currently be sown in all of autumn and spring, but to be able to sow it in late summer, then you need to change the growth file. 

in
' <gt growthTransitionNum="7"> 

' change <fruit fruitName="rape"    normalGrowthState="5" normalGrowthMaxState="6" setGrowthState="1"  desiredGrowthState="CUT"/>

to

'<fruit fruitName="rape"    normalGrowthState="1" normalGrowthMaxState="6"/>

**Comment by SimulatorGAMES** [comment]
For the barley that must be set as value to go directly to stage 7
, To do exactly as in the picture.

**Comment by theSeb1979** [comment]
It is not realistic to be able to harvest all summer. Harvest in real life in the northern climate starts in August and goes on until autumn. Some times, in lucky years, harvest can start in late July (mid summer). If you want to harvest throughout summer, then you need to modify the growth so that it reaches stage 7 in the late spring to early summer transition.

**Comment by SimulatorGAMES** [comment]
It's not a question of realism, we live in southern france and the harvest is over on July 14th. It is to adapt your mod to our way of playing, It's to give us more time to work in the fields....

**Comment by theSeb1979** [comment]
I understand that. The growth is based on England. To achieve what you want to do is get to final growth stage earlier, like I said above :)

The final growth stage for canola and barley is 7

**Comment by joskuijpers** [comment]
There is quite some distance between southern france and northern england.

You can make your own weather and growth configurations and use them. See our example GEO mod.

**Comment by SimulatorGAMES** [comment]
You can change the growth.xml for us?
To do as in the photo, because after 2 weeks try it still does not work our settings. :(
Please, otherwise we abandon the mod season, it is too complicated and not realized for the French players.
Or do a tutorial that explains what it means:
- "normalGrowthState"
- "normalGrowthMaxState"
- "setGrowthState"

**Comment by joskuijpers** [comment]
You can read more at https://github.com/RealismusModding/FS17_seasons/issues/289#issuecomment-297388778

We are still developing the mod. Once we are doing we will be writing documentation on customizing it. It is not a priority right now.

You could try to play with the current settings, and have some fun with that. In the overview you can read when you can plant, and in the game overview you can see how far your crops are. If they are in the very latest harvest state, you can harvest them.
Plant as early as is possible so that the crops are ready early enough.
