### ISSUE TITLE
How does work the "SeasonAdmirer"

### ISSUE THREAD

**Issue by SimulatorGAMES** [RealismusModding/FS17_seasons#463]
Hello,
I would like that some model 3d only display in the winter, I understood to use the function "SeasonAdmirer".
How does this function work?

It is a name that it fails to put in the 3d on Giant Editor, or an .xml, or in the "UserAttribute" of the 3D on the map?
Sorry for my English, I'm french ....e 3D on the map?

Hugo,

**Comment by joskuijpers** [comment]
Alright, I will give an explanation.

There are a couple of 'objects', one is ssSeasonAdmirer.
To show an object in just 1 or more seasons, do this in GE:

- Click on the object
- Go to the User Attributes
- Add a new user attribute, of type `script`
  - name it: `onCreate`
  - value must be: `ssSeasonAdmirer.onCreate`
- Add another user attribute of type `boolean`
  - name it: 'spring'
  - value is: checked if you want to show it in spring, unchecked if you dont
- Do this for `autumn`, `summer`, and `winter` as well

Save, run :D

### If you are making a map you want to publish:
If you do not want to show the object when seasons is not running, set it invisible in GE. If it has a collision, you need to add the script in `modding/` to your map as well, so the collision is disabled when seasons is not found. (Otherwise you run against invisible snowman)

## Ice planes
To add an ice plane, use `ssIcePlane.onCreate` instead of `ssSeasonAdmirer.onCreate`. No other user attributes needed

## Snow admirer
To add an object that is only visible when there is snow, use `ssSnowAdmirer.onCreate`. 
If you want to hide it when there is snow, and show when there is no snow, add a boolean user attribute named `snow` and set it to `unchecked`.
