### ISSUE TITLE
need to store previous will germinate data when a job is put on the queue

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#471]
If fast forwarding, previous germinate data will not be correct.

**Comment by joskuijpers** [comment]
Is there anything I can provide to help with this? DMS changes? Maybe we can store the data outside the dms with an attribute for the day it is bound to?

**Comment by theSeb1979** [comment]
No it's all good. Fix is easy for me to do. Will do it tomorrow night.

**Comment by joskuijpers** [comment]
So I wonder, what happens if 4 growth events are queued, and then the game is saved?

**Comment by joskuijpers** [comment]
Also, after a while that previous germ table gets bigger and bigger.

Isn't there a moment a GT can be removed? After finishing a growth (using a finalizer)?
Can't we then store that whole table in the savegame. If it is played normally it is the same as it is now. Otherwise, it is huge.

And another question, how does this go from an 1.0 savegame to a 1.1 savegame?

**Comment by theSeb1979** [comment]
It will get as big as 12. If somebody fast forwards that much, then I need all of those. 

I'll look into removing values.

Savegame... I need to think about this... may need to bump up the save game version.

**Comment by theSeb1979** [comment]
done
