### ISSUE TITLE
[GM] Performance improvements

### ISSUE THREAD

**Issue by theSeb1979** [RealismusModding/FS17_seasons#51]
When the initial reset occurs, FPS drops from 160 to 60. Also fps drops during growth periods. Need to improve.

**Comment by mrbear** [comment]
Both Soilmod and Growth manager had similar problems.

They solved it by:
1. Do growth at midnight when players are less active.
2.  Show progress/progress information to the player to make them aware of what's going on.

Doing massive updates of density layers will always have effects on performance. What you can try is decreasing the area done in each update and spread then out over longer time, but if it still affects gameplay it might actually be worse than taking a bigger hit during a limited time window.

**Comment by Dzi4d3k** [comment]
Just to notice - indeed SoilMods shows progress of SoilMod layers calculation, but it splits map into squares. Because of such functionality we had some issue where savegame was made during such calculation and we had revert to such savegame. Our map looked like checkerboard. However I think that such approach minimize performance impact.

**Comment by mrbear** [comment]
@Dzi4d3k That's exactly what we do already.

The problem is that we either have to make the chunks small enough to fit within 1/framerate seconds with good margin on the slowest supported computer and still leave enough time for everything else that have to be done for each frame. For any normal player the frame rate will  be limited to 60 FPS so that gives us the amount of time that we have to squeeze the updates into. The alternative is to accept stuttering during a short time window and inform the player what's going on.

Regarding saves during an update, the first thing we could do is to inform the user what's going on and to avoid saving during this window. The second solution would be to serialize the progress of the update in the save game.  A third possibility is to see if we could disable save when doing these updates.

**Comment by joskuijpers** [comment]
The last one I can easily do. I can override the save button. But then there is the problem of autosave..

**Comment by mrbear** [comment]
Could you catch and delay the autosave?

**Comment by joskuijpers** [comment]
FSCareerMissionInfo.saveToXML(...)
Is a thing. I do something with it already (our own saving).
I could make it not-work, probably, when I want to.
Should do the save later then, otherwise it gets weird for server managers.

**Comment by mrbear** [comment]
Just verify that it also manages the save of the densitymaps and possibly other things as we otherwis6e might end up with a corrupted or inconsistent savegame.

**Comment by joskuijpers** [comment]
Hmm I don’t think it will. And can’t find much about it either. But I do know that autosave is not the same folder as the normal save.

**Comment by mrbear** [comment]
@Dzi4d3k thanks for pointing out the problem with partial updates when saving the game in the middle of an update while scanning the map. We now have a design proposal to make it possible to continue the update where it left of when saving the game and will try to implement it to see if we can make it work.

**Comment by theSeb1979** [comment]
Refactored GM to use ssDensityMapScanner. this should resolve most issues. closing this issue and keeping the other one open.
