### ISSUE TITLE
[GM] Breaks in multiplayer

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#62]
The data is not correctly sent to the client. Possibly update everything at once when on a dedi?

**Comment by Dzi4d3k** [comment]
I would be happy to test this mod with friends on our dedicated server, but I don't want to annoy them.
Is it ready for beta tests or should I put off test yet?

**Comment by mrbear** [comment]
I would say that the data is correctly sent to the client, it will eventually get to a correct state but it will take a minute or two.
The problem is that it takes a while to sync the data over, possibly due to the amount of updates that we are doing in a short period of time. We have to look into this to see if it can be improved.

@Dzi4d3k There's still quite a lot of bugs to weed out until it's any point trying Mp with more than one player. There are still things that's obviously broken with a single player on a dedicated server, as in the game is currently unplayable with the mod. Give us some time to weed the bugs out first if you expect to be able to play anything like a normal game.

**Comment by Dzi4d3k** [comment]
OK, I'm then keeping fingers crossed, as for now this is everything, that I can do to support you guys.
