### ISSUE TITLE
Improve prices menu info to not contradict with economy

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#721]

**Comment by joskuijpers** [comment]
I suggest we look into adding new columns, or improving the columns. Maybe just show the price that always was and omit that heaps are 0$ anywhere but in the manual/helpline?

**Comment by dominiczeth** [comment]
Just wanted to report that the Season Prive Menu calculates "0€" Sellpoints for the average price of a fruit. this way i got really low prices when usinf BGA Extension, because there nearly every Fruit is "Sellable" in the BGA but for 0€. Is this mentioned above the Fix too? It shouldn't calculate 0€ Prices for a Fruit for the average Price in the yearly overview.

**Comment by joskuijpers** [comment]
With 'fruit', do you mean heaps of straw, hay and grass, or things like wheat?

**Comment by dominiczeth** [comment]
Iean things like wheat. Just an example: I have a map with 2 sell points for rape. Prices are 1600 and 1400. But in the overview where you see the diagram for the whole year it shows me a price of 1000 for that day. Problem is I have the bga extension. And with that you can also put rape in the bga bunker. But for a 0€ price because the calculations is done by the bga extension script. But the season overview calculates the average. So it's like (1600+1400+0)/3=1000. But it should be(1600+1400)/2=1500 average. So it shouldn't use 0€ sell prices for calculations.

**Comment by joskuijpers** [comment]
I will have to think about that solution, to see if it does not negatively influence games without BGA extension.

**Comment by dominiczeth** [comment]
Yeah would be nice :) isn't it just possible to use only values >1 for the calculation? This way games without bga extension will work too. But I'm not a scripter, I know a bit about programming but not in depth.

**Comment by joskuijpers** [comment]
Does the BGA show 0$ prices in the prices menu?

**Comment by dominiczeth** [comment]
Yes it shows 0€ for every fruit you can put in. Also for silage.

**Comment by joskuijpers** [comment]
Yes that might then be an issue... why doesn't BGA extension implement this correctly and show the actual value?

**Comment by dominiczeth** [comment]
That's an easy explanation: bga extension don't give you money for the fruits you put in. It runs like a real one so you don't get money for the filling itself, you get the money for running and how it runs. So you get less money when you start it and more when it runs longer. Also you get bonus  for manure / liquid manure.

**Comment by joskuijpers** [comment]
Then it should configure its 'sellpoints' so that it doesnt show up in the prices list. There is an xml option for that.

If it does that, I can do: `ignore if 0 and not shown on prices list` which seems more future proof to me

**Comment by dominiczeth** [comment]
Your second solution would be best because on the map I play a heatplant uses a very similar script and shows also 0 in the hud.

I tried to use "false" for show on hud but it's still calculated in season mod.

**Comment by joskuijpers** [comment]
Alright, I made a change. Could you see if this works correctly and did not break anything?

**Comment by dominiczeth** [comment]
Yes will try it this evening when I'm at home.

**Comment by Dzi4d3k** [comment]
Being just curious, will it erase also sell points accepting loose straw?

**Comment by joskuijpers** [comment]
Yes, these are already 0, but we default to 0 if we don't find any viable sellpoints, so the result will be 0 still.

Using the update is 'if the price is 0, we assume you don't actually sell there' for purposes of the price history (economy page)

**Comment by dominiczeth** [comment]
Ok i just tried it with my old Savegame and with a new one on a Mod Map. And both times it worked aut of the Box. Just the Prive for Silage is strange because it's at 450€, I think it's because the only Sellpoint is the BGA and there it's 0€. But that's not a problem for me, i don't look there anyway. Will test now a bit longer on my Savegame to see if there is something wrong.
