### ISSUE TITLE
How do you add Additional Fruits in GEOs?

### ISSUE THREAD

**Issue by nyfarmboy07** [RealismusModding/FS17_seasons#751]
I have attempted to create a GEO mod to add additional fruits, but I have been unsuccessful.  No where in the manual can I find anything about additional crops except that they will default to using the barley crop growth table.

**Comment by joskuijpers** [comment]
Yes, we have not had the time yet to write that manual.

There are others that have succeeded: you might be able to ask on the forums. There are also a couple of issues on this GitHub with more information.

**Comment by theSeb1979** [comment]
In your xml file you should have copied the original growth.xml. 

Two important sections that need to be considered first.

```
<defaultFruits>
        <defaultFruit fruitName="barley" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="wheat" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="rape" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="maize" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="soybean" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="sunflower" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="potato" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="sugarBeet" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="poplar" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="grass" maxSprayGrowthState="4"/>
        <defaultFruit fruitName="oilseedRadish" />
        <defaultFruit fruitName="dryGrass" />
        <defaultFruit fruitName="sugarCane" />
    </defaultFruits>
```

and at the bottom

<germination>
        <fruit fruitName="barley" germinateTemp="5" />
        <fruit fruitName="wheat" germinateTemp="5" />
        <fruit fruitName="rape" germinateTemp="5" />
        <fruit fruitName="maize" germinateTemp="10" />
        <fruit fruitName="soybean" germinateTemp="10" />
        <fruit fruitName="sunflower" germinateTemp="7" />
        <fruit fruitName="potato" germinateTemp="5" />
        <fruit fruitName="sugarBeet" germinateTemp="5" />
        <fruit fruitName="grass" germinateTemp="3" />
        <fruit fruitName="oilseedRadish" germinateTemp="7" />
        <fruit fruitName="poplar" germinateTemp="5" />
        <fruit fruitName="sugarCane" germinateTemp="12" />
    </germination>

You need to add your fruit in the top section by creating a new line like <defaultFruit fruitName="newFruit" maxSprayGrowthState="4"/> and set the number to whatever you want as long as it is below the harvestable state. This number basically restricts up to when you can spray/fertilise a crop. By default I chose 4 which is the last growing state in the game.

In the bottom section you also need to add a new line and input the correct germination temperature for it, like this <fruit fruitName="newFruit" germinateTemp="5" />

Then you need to model the fruit's growth and put in the appropriate commands for each growth state in the <growthTransitions> section

It's important to consider how the fruit has been added, how many states it has and what are the min and max harvestable states in order to model the growth properly. Each <gt> is what will happen at the beginning of that transition. In other words, gt 1 is what will happen when you go from late winter to early spring, gt 2 is what will happen when you go from early spring to mid spring and so forth.
