### ISSUE TITLE
Add 3 types of snow: none, 1 layer max, full

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#94]
1 layer automatically on MP
1 layer automatically on snow mask.

**Comment by mrbear** [comment]
Are there a background discussion somewhere to describe what this is all about and why? Should I read this as a suggestion to limit snow to one layer in Multiplayer and in that case why, are you experiencing performance problems when testing?

**Comment by joskuijpers** [comment]
Hi,

Well, that is the plan. Was working on that.
I have not experienced problems myself, but I heard Daggerwin say he has problems with tip Anywhere on his 10 player server already.
And we now have Snow Tracks: when a vehicle drivers over snow, the snow is compressed (looks awesome), and the tractor has less traction. This however means that driving in the snow will cause constant density map updates. With 4 players or even more, this might cause serious issues.
Snow tracks do not apply to snow with 1 layer or less.

**Comment by mrbear** [comment]
Test and verify before assuming things. The same problem should happen any operation affecting crops or soin so then any game with more than a few active players should have the problem. Unless they are just carting crops around between silos. 

I would say that 90% of the full map updates for the snow are removing snow rather than adding, and unless you drop all heaps at the first remove i.e. binary snow or no snow the few extra updates to add  layers of snow would not matter.

If the problem actually shows up to be the Snow tracks, would it not make more sense to disable them in multiplayer directly rather than indirectly by limiting the snow depth?

**Comment by joskuijpers** [comment]
Yeah, good idea. :)
