### ISSUE TITLE
When a placeable is placed on a snow masked area, snow will fall after placeable is removed

### ISSUE THREAD

**Issue by joskuijpers** [RealismusModding/FS17_seasons#95]

**Comment by mrbear** [comment]
Yes it works that way since it manipulates the same snowmask. Normally that would not be much of a problem since the areas masked by the snowmask will be areas covered by objects so placables can not be placed there anyway. But of course map makers might do crasy things.

I suggest we solve it by documenting the behaviour. The alternative would be to somehow have yet another mask to keep track of what areas where dynamically added.

**Comment by joskuijpers** [comment]
Ah you mean that everywhere a player can place objects, snow must reach as well?

How about placing someting inside a shed? Is that even possible? (Trying now)

**Comment by mrbear** [comment]
Yes, I think that would be good enough and that we should close this with won't fix at least for v1.

**Comment by joskuijpers** [comment]
It is actually not a bug. You can't place a placeable inside a placeable. And you can't place placeables inside other buildings like the cow shed. Anything else is not a problem
